### ISSUE TITLE
Finish comments in functions.py

### ISSUE THREAD

**Issue by crisjf** [ils246/SCM#2]
I am not sure what countby function does? @ils246

**Comment by ils246** [comment]
The countby function is used for the memories. It takes all the agent's memories and makes a dictionary that tells me how many agents have 1 idea, 2 ideas etc...

This was so that I could get the distribution without having to deal with a huge file. But I do think that I might not end up using it if we need to record every agent's memory in time.

The file looks like this (one dictionary for each p value):

`[{"0": 3, "1": 2, "2": 6, "4": 2, "5": 6, "6": 1, "7": 5, "8": 2, "9": 7, "10": 3, "11": 5, "12": 14, "13": 41, "14": 3}, {"0": 3, "2": 2, "3": 2, "5": 3, "7": 2, "8": 4, "9": 5, "10": 3, "11": 6, "12": 3, "13": 67}, {"1": 3, "4": 1, "6": 1, "9": 1, "10": 2, "11": 2, "12": 4, "13": 3, "14": 5, "15": 60, "16": 18}, {"3": 2, "4": 1, "6": 1, "8": 2, "10": 2, "11": 3, "12": 81, "13": 8}, {"3": 1, "4": 2, "8": 1, "9": 1, "10": 1, "11": 1, "14": 2, "16": 5, "17": 86}, {"0": 1, "3": 1, "4": 1, "6": 2, "7": 1, "8": 1, "10": 1, "11": 5, "12": 87}, {"9": 96, "2": 1, "3": 1, "5": 1, "7": 1}, {"11": 1, "9": 1, "3": 2, "12": 96}, {"0": 1, "9": 1, "10": 1, "11": 97}, {"8": 1, "9": 97, "2": 1, "7": 1}, {"6": 100}, {"4": 100}, {"5": 100}, {"9": 100}, {"6": 100}, {"2": 100}, {"3": 100}, {"2": 100}, {"0": 100}, {"0": 100}]`

**Comment by crisjf** [comment]
What is f and what is seq? the two input parameters of this function?

**Comment by ils246** [comment]
f is the function, and seq is the sequence of items that you are going to be counting. So in our case, f is len() and seq is memories because you want to know how many ideas each agent has. 

However, did you see the new memories code I added? I think that is more like what we need so we may not end up using this function at all. Thoughts?

**Comment by crisjf** [comment]
I changed the code a little bit and finished de documentation. Please take a look and if it is doing what it should be doing, then close this issue.
thanks!

**Comment by ils246** [comment]
I don't think we are going to end up using that function, Jara. Thanks anyway.
